theme = "tokyonight"

[editor]
line-number = "relative"
bufferline = "multiple"
color-modes = true
cursorline = true
idle-timeout = 50

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false # counter-intuitively, this ALLOWs hidden files, i.e., it's really "ignore hidden? false"

[editor.indent-guides]
render = true

[editor.lsp]
# turning inlay hints off again, it's just too noisy in javascript
# display-inlay-hints = true

[editor.soft-wrap]
enable = true

[editor.statusline]
right = ["diagnostics", "selections", "register", "position", "position-percentage", "total-line-numbers"]
center = ["version-control"]

[keys.normal]
C-y = ":sh zellij run -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh"
